package com.registadb;

import registadb.Playbook.LogEntry; // This will be generated by Maven
import java.io.FileOutputStream;

public class Producer {
    public static void main(String[] args) throws Exception {
        // 1. Build the message
        LogEntry entry = LogEntry.newBuilder()
            .setId(202)
            .setCategory("JAVA_PRODUCER")
            .setContent("Hello from the Java Playmaker!")
            .setTimestamp(System.currentTimeMillis())
            .build();

        // 2. For now, we'll save it to a file that C++ can read
        // (Next we will do this over a network socket)
        try (FileOutputStream output = new FileOutputStream("../data/java_play.bin")) {
            entry.writeTo(output);
        }

        System.out.println("Java: Message serialized and saved to ../data/java_play.bin");
    }
}