package com.registadb;

import registadb.Playbook.LogEntry; // This will be generated by Maven
import java.io.FileOutputStream;
import org.zeromq.ZMQ;
import org.zeromq.ZContext;

public class Producer {
    public static void main(String[] args) throws Exception {
        try (ZContext context = new ZContext()) {
            ZMQ.Socket socket = context.createSocket(ZMQ.PUSH);
            socket.connect("tcp://localhost:5555"); // Connect to the C++ engine

            LogEntry entry = LogEntry.newBuilder()
                .setId(311)
                .setCategory("NETWORK_PLAY")
                .setContent("Sent over ZeroMQ!")
                .setTimestamp(System.currentTimeMillis())
                .build();

            socket.send(entry.toByteArray());
            System.out.println("Java: Pushed message to C++ over port 5555");
        }
    }
}